[2025-10-18T04:35:07.594+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.distribution.send_email_alerts manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:35:07.598+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.distribution.send_email_alerts manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:35:07.599+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-10-18T04:35:07.604+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): distribution.send_email_alerts> on 2025-10-18 02:31:24.144743+00:00
[2025-10-18T04:35:07.608+0000] {standard_task_runner.py:57} INFO - Started process 1244 to run task
[2025-10-18T04:35:07.610+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agricultural_sri_annual_report', 'distribution.send_email_alerts', 'manual__2025-10-18T02:31:24.144743+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/agricultural_sri_pipeline.py', '--cfg-path', '/tmp/tmp1o7_0xwx']
[2025-10-18T04:35:07.611+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask distribution.send_email_alerts
[2025-10-18T04:35:07.634+0000] {task_command.py:416} INFO - Running <TaskInstance: agricultural_sri_annual_report.distribution.send_email_alerts manual__2025-10-18T02:31:24.144743+00:00 [running]> on host 4e2b74bc69c8
[2025-10-18T04:35:07.651+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-10-18T04:35:07.672+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alerts@agcompany.com' AIRFLOW_CTX_DAG_OWNER='agricultural_risk_team' AIRFLOW_CTX_DAG_ID='agricultural_sri_annual_report' AIRFLOW_CTX_TASK_ID='distribution.send_email_alerts' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T02:31:24.144743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T02:31:24.144743+00:00'
[2025-10-18T04:35:07.677+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-10-18T04:35:07.677+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-10-18T04:35:10.142+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 280, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-292471d5794sm12135695ad.53 - gsmtp')
[2025-10-18T04:35:10.159+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=agricultural_sri_annual_report, task_id=distribution.send_email_alerts, execution_date=20251018T023124, start_date=20251018T043507, end_date=20251018T043510
[2025-10-18T04:35:10.170+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task distribution.send_email_alerts ((535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-292471d5794sm12135695ad.53 - gsmtp'); 1244)
[2025-10-18T04:35:10.198+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-18T04:35:10.219+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
