[2025-10-18T04:22:30.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.report_generation.generate_market_summary manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:22:30.613+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.report_generation.generate_market_summary manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:22:30.613+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-10-18T04:22:30.621+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): report_generation.generate_market_summary> on 2025-10-18 02:31:24.144743+00:00
[2025-10-18T04:22:30.624+0000] {standard_task_runner.py:57} INFO - Started process 986 to run task
[2025-10-18T04:22:30.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agricultural_sri_annual_report', 'report_generation.generate_market_summary', 'manual__2025-10-18T02:31:24.144743+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/agricultural_sri_pipeline.py', '--cfg-path', '/tmp/tmp4h8x2kpz']
[2025-10-18T04:22:30.627+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask report_generation.generate_market_summary
[2025-10-18T04:22:30.650+0000] {task_command.py:416} INFO - Running <TaskInstance: agricultural_sri_annual_report.report_generation.generate_market_summary manual__2025-10-18T02:31:24.144743+00:00 [running]> on host 4e2b74bc69c8
[2025-10-18T04:22:30.682+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alerts@agcompany.com' AIRFLOW_CTX_DAG_OWNER='agricultural_risk_team' AIRFLOW_CTX_DAG_ID='agricultural_sri_annual_report' AIRFLOW_CTX_TASK_ID='report_generation.generate_market_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T02:31:24.144743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T02:31:24.144743+00:00'
[2025-10-18T04:22:30.921+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/agricultural_sri_pipeline.py", line 436, in generate_market_summary
    from market_report_generator import generate_summary_report
ImportError: cannot import name 'generate_summary_report' from 'market_report_generator' (/opt/airflow/dags/scripts/reporters/market_report_generator.py)
[2025-10-18T04:22:30.928+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=agricultural_sri_annual_report, task_id=report_generation.generate_market_summary, execution_date=20251018T023124, start_date=20251018T042230, end_date=20251018T042230
[2025-10-18T04:22:30.935+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task report_generation.generate_market_summary (cannot import name 'generate_summary_report' from 'market_report_generator' (/opt/airflow/dags/scripts/reporters/market_report_generator.py); 986)
[2025-10-18T04:22:30.975+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-18T04:22:30.987+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
